name: takehome_app_synergies
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.12
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.0+2
  cached_network_image: ^2.4.1
  flutter_webview_plugin: ^0.3.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true